### PR TITLE
Support SpriteAtlas

### PR DESCRIPTION
**Pull request by xiabob**
Try to support "SpriteAtlas" for #40

### CODE REVIEW

**Comment by xiabob** [comment]
maybe also work for #13

**Comment by kirevdokimov** [comment]
Hi, thank you for your contribution!

I see many indentation issues, can you solve them before we can merge it?

**Comment by xiabob** [comment]
Very strange, I actually didn't make any changes to this part of the content, but the formatting did change. I've pull a new commit, reformatting the code.

**Comment by kirevdokimov** [comment]
Thank you @xiabob! I hope you tested all presented scenarios because I can no longer check builds by myself. Let me know if it is and we can merge it :)

**Comment by xiabob** [comment]
I tested it on my Android device, and it worked as expected.

**Comment by kirevdokimov** [comment]
Hi, @xiabob, sorry for the late response. I merged your request, thank you for your contribution!

**Pull request merged**
